# Makefile Template for Helm Chart Repositories
# Generated by build-workflow v2
# https://github.com/orhayoun-eevee/build-workflow

.PHONY: help deps lint test golden golden-update kubeconform checkov validate ci update-scripts

# Configuration
SCRIPTS_REPO = https://raw.githubusercontent.com/orhayoun-eevee/build-workflow
SCRIPTS_VERSION ?= v2.0.0
CHART_PATH ?= .

help: ## Show this help message
	@echo "Available targets:"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'

update-scripts: ## Update validation scripts from build-workflow
	@echo "Syncing validation scripts from build-workflow $(SCRIPTS_VERSION)..."
	@mkdir -p scripts
	@for script in common.sh lint.sh golden.sh kubeconform.sh version-check.sh checkov.sh; do \
		curl -fsSL $(SCRIPTS_REPO)/$(SCRIPTS_VERSION)/scripts/$$script -o scripts/$$script && \
		chmod +x scripts/$$script && \
		echo "✓ Updated scripts/$$script"; \
	done
	@echo ""
	@echo "Scripts updated successfully!"
	@echo "Remember to commit: git add scripts/ && git commit -m 'Update validation scripts to $(SCRIPTS_VERSION)'"

deps: ## Update Helm chart dependencies
	@echo "Updating test-chart dependencies..."
	@helm dependency update test-chart

lint: ## Run helm lint on both charts
	@echo "Linting libChart and test-chart..."
	@./scripts/lint.sh --strict --additional libChart test-chart

test: deps ## Run helm unittest on test-chart
	@echo "Running unit tests..."
	@helm unittest test-chart

golden: ## Compare generated manifests against golden snapshot
	@echo "Checking golden snapshot..."
	@./scripts/golden.sh test-chart

golden-update: ## Update golden snapshot file
	@echo "Updating golden snapshot..."
	@./scripts/golden.sh --update test-chart

kubeconform: ## Validate manifests with kubeconform
	@echo "Validating with kubeconform..."
	@./scripts/kubeconform.sh test-chart

checkov: ## Run Checkov security checks (soft-fail)
	@echo "Running Checkov security checks..."
	@./scripts/checkov.sh --soft-fail test-chart

validate: lint golden kubeconform ## Run all validation checks
	@echo ""
	@echo "✓ All validation checks passed!"

ci: deps test validate checkov ## Run full CI suite (deps + test + validate + checkov)
	@echo ""
	@echo "✓ All CI checks passed!"

pre-push: ci ## Pre-push checks (runs ci and checks for uncommitted golden changes)
	@echo "Checking for uncommitted golden file changes..."
	@if ! git diff --exit-code tests/golden.yaml gold/gold_file.yaml > /dev/null 2>&1; then \
		echo ""; \
		echo "❌ Error: Golden file has uncommitted changes!"; \
		echo ""; \
		echo "Review changes with: git diff tests/golden.yaml gold/gold_file.yaml"; \
		echo ""; \
		echo "If the changes are expected:"; \
		echo "  1. Review the diff carefully"; \
		echo "  2. git add tests/golden.yaml (or gold/gold_file.yaml)"; \
		echo "  3. git commit"; \
		echo ""; \
		exit 1; \
	fi
	@echo ""
	@echo "✓ All pre-push checks passed! Safe to push."
